package com.gyro.tests

/* DO NOT EDIT | Generated by gyro */

import io.realm.RealmObject
import io.realm.annotations.PrimaryKey
import io.realm.annotations.Required

open class Product : RealmObject() {

    object Attributes {
        const val NAME: String = "name"
        const val BRAND: String = "brand"
        const val PRICE: String = "price"
    }

    @PrimaryKey
    var name: String = ""
    @Required
    var brand: String = ""
    var price: Int = 0
}
