package com.gyro.tests

/* DO NOT EDIT | Generated by gyro */

import io.realm.RealmList
import io.realm.RealmObject
import io.realm.annotations.PrimaryKey
import io.realm.annotations.Required

class Shop : RealmObject() {

    object Attributes {
        const val NAME: String = "name"
    }

    object Relationships {
        const val PRODUCTS: String = "products"
    }

    @PrimaryKey
    var name: String = ""
    var products: RealmList<Product>? = null
}
