package com.gyro.tests

/* DO NOT EDIT | Generated by gyro */

import java.util.Date

import io.realm.RealmObject
import io.realm.annotations.PrimaryKey
import io.realm.annotations.Required

open class User : RealmObject() {

    object Attributes {
        const val NAME: String = "name"
        const val BIRTHDAY: String = "birthday"
    }

    object Relationships {
        const val FIDELITY_CARD: String = "fidelityCard"
    }

    @PrimaryKey
    var name: String = ""
    @Required
    var birthday: Date = Date()
    var fidelityCard: FidelityCard? = null
}
