package com.gyro.tests;

/* DO NOT EDIT | Generated by gyro */

import io.realm.RealmObject;
import io.realm.annotations.Required;

public class Dog extends RealmObject {

    public static final class Attributes {
        public static final String AGE = "age";
        public static final String NAME = "name";

        private Attributes() {
            // Hide constructor
        }
    }

    private short age = 0;
    @Required
    private String name;

    public short getAge() {
        return age;
    }

    public void setAge(final short age) {
        this.age = age;
    }

    public String getName() {
        return name;
    }

    public void setName(final String name) {
        this.name = name;
    }
}
