package com.gyro.tests;

import io.realm.RealmObject;

/* DO NOT EDIT | Generated by gyro */

public class Dog extends RealmObject {

    public static class Attributes {
        private Attributes() {
            // Hide constructor
        }

        public static final String AGE = "age";
        public static final String NAME = "name";
    }

    private short age;
    private String name;

    public short getAge() {
        return age;
    }

    public void setAge(final short age) {
        this.age = age;
    }

    public String getName() {
        return name;
    }

    public void setName(final String name) {
        this.name = name;
    }



}
