package fr.ganfra.realm;

import io.realm.RealmList;
import io.realm.RealmObject;

/* DO NOT EDIT | Generated by dbgenerator */

public class Person extends RealmObject {

    public interface Relationships {
        String DOGS = "dogs";
    }

    private RealmList<Dog> dogs;

    public RealmList<Dog> getDogs() {
        return dogs;
    }

    public void setDogs(final RealmList<Dog> dogs) {
        this.dogs = dogs;
    }
}
