package com.gyro.tests

/* DO NOT EDIT | Generated by gyro */

import com.google.gson.annotations.SerializedName

import io.realm.RealmObject
import io.realm.annotations.Required

open class Shop : RealmObject() {

    object Attributes {
        const val NAME: String = "name"
        const val TYPE: String = "type"
        const val TYPE_OPTIONAL: String = "typeOptional"
    }

    @Required
    var name: String = ""
    @Required
    @SerializedName("type")
    var type: String = "TypeOne"
    @SerializedName("typeOpt")
    var typeOptional: String? = null

    fun getTypeEnum(): Type? = Type.get(type)

    fun setTypeEnum(type: Type) {
        this.type = type.jsonValue
    }

    fun getTypeOptionalEnum(): Type2? = Type2.get(typeOptional)

    fun setTypeOptionalEnum(typeOptional: Type2) {
        this.typeOptional = typeOptional.jsonValue
    }
}
