package com.gyro.tests;

import io.realm.RealmObject;

/* DO NOT EDIT | Generated by gyro */

public class Product extends RealmObject {

    public static class Relationships {
        private Relationships() {
            // Hide constructor
        }

        public static final String SHOP = "shop";
    }

    private Shop shop;

    public Shop getShop() {
        return shop;
    }

    public void setShop(final Shop shop) {
        this.shop = shop;
    }

}
