// DO NOT EDIT | Generated by dbgenerator

////////////////////////////////////////////////////////////////////////////////

#pragma mark - Imports

#import "RLMShop+JSON.h"

////////////////////////////////////////////////////////////////////////////////

#pragma mark - Implementation

@implementation RLMShop (JSON)

+ (NSDictionary *)JSONInboundMappingDictionary
{
    return @{
        @"isOpened" : @"isOpened",
        @"isValid" : @"isValid",
        @"name" : @"name"
    };
}

+ (NSDictionary *)JSONOutboundMappingDictionary
{
    return @{
        @"isOpened" : @"isOpened",
        @"isValid" : @"isValid",
        @"name" : @"name"
    };
}

+ (NSValueTransformer *)isOpenedJSONTransformer
{
    return [MCJSONValueTransformer valueTransformerWithMappingDictionary:@{
        @"null" : @(NO),
        [NSNull null] : @(NO),
        @"<null>" : @(NO),
        @"false" : @(NO),
        @"true" : @(YES),
        @(NO) : @(NO),
        @(YES) : @(YES)
    }];
}

+ (NSValueTransformer *)isValidJSONTransformer
{
    return [MCJSONValueTransformer valueTransformerWithMappingDictionary:@{
        @"null" : @(NO),
        [NSNull null] : @(NO),
        @"<null>" : @(NO),
        @"false" : @(NO),
        @"true" : @(YES),
        @(NO) : @(NO),
        @(YES) : @(YES)
    }];
}

@end
