// DO NOT EDIT | Generated by dbgenerator

////////////////////////////////////////////////////////////////////////////////

#pragma mark - Imports

#import <Realm/Realm.h>

#pragma mark - Types

@class RLMPerson;

#pragma mark - Defines & Constants

extern const struct RLMDogAttributes {
    __unsafe_unretained NSString *age;
    __unsafe_unretained NSString *name;
} RLMDogAttributes;

////////////////////////////////////////////////////////////////////////////////

#pragma mark - Interface

@interface RLMDog : RLMObject

#pragma mark - Properties

@property int age;
@property NSString *name;
@property (readonly) RLMPerson *owner;

@end
