// DO NOT EDIT | Generated by dbgenerator

////////////////////////////////////////////////////////////////////////////////

#pragma mark - Imports

#import "RLMDog.h"

#pragma mark - Defines & Constants

const struct RLMDogAttributes RLMDogAttributes = {
    .age = @"age",
    .name = @"name"
};

////////////////////////////////////////////////////////////////////////////////

#pragma mark - Implementation

@implementation RLMDog

#pragma mark - Superclass Overrides

// Specify required properties
+ (NSArray *)requiredProperties
{
    return @[@"age", @"name"];
}

// Specify default values for required properties
+ (NSDictionary *)defaultPropertyValues
{
    return @{@"age" : @(0), @"name" : @""};
}

- (RLMPerson *)owner
{
    return [[self linkingObjectsOfClass:@"RLMPerson" forProperty:@"dogs"] objectAtIndex:0];
}

@end
