// DO NOT EDIT | Generated by dbgenerator

////////////////////////////////////////////////////////////////////////////////

#pragma mark - Protocols

// This protocol enables typed collections. i.e.: RLMArray<RLMDog>
RLM_ARRAY_TYPE(RLMDog)
