// DO NOT EDIT | Generated by gyro

////////////////////////////////////////////////////////////////////////////////

#pragma mark - Imports

#import "RLMPerson.h"

#pragma mark - Defines & Constants

const struct RLMPersonRelationships RLMPersonRelationships = {
    .dogs = @"dogs"
};

////////////////////////////////////////////////////////////////////////////////

#pragma mark - Implementation

@implementation RLMPerson

@end
