// DO NOT EDIT | Generated by dbgenerator

////////////////////////////////////////////////////////////////////////////////

#pragma mark - Imports

#import <Realm/Realm.h>
#import "RLMProtocols.h"

#pragma mark - Types

@class RLMDog;

#pragma mark - Defines & Constants

extern const struct RLMPersonRelationships {
    __unsafe_unretained NSString *dogs;
} RLMPersonRelationships;

////////////////////////////////////////////////////////////////////////////////

#pragma mark - Interface

@interface RLMPerson : RLMObject

#pragma mark - Properties

@property RLMArray<RLMDog> *dogs;

@end
