/* DO NOT EDIT | Generated by gyro */

import RealmSwift
import Foundation

final class Product: Object {

  enum Relationships: String {
    case shop = "shop"
  }

  @objc dynamic var shop: Shop?

}
