/* DO NOT EDIT | Generated by gyro */

import RealmSwift
import Foundation

final class Shop: Object {

    enum Attributes: String {
        static let AttrDate = "attrDate"
        static let AttrDateCustom = "attrDateCustom"
        static let AttrDecimal = "attrDecimal"
        static let AttrDouble = "attrDouble"
        static let AttrFloat = "attrFloat"
        static let AttrInteger16 = "attrInteger16"
        static let AttrInteger32 = "attrInteger32"
        static let AttrInteger64 = "attrInteger64"
    }

    @objc dynamic var attrDate: NSDate? = nil
    @objc dynamic var attrDateCustom: NSDate? = nil
    @objc dynamic var attrDecimal: Double = 0.0
    @objc dynamic var attrDouble: Double = 0.0
    @objc dynamic var attrFloat: Float = 0.0
    @objc dynamic var attrInteger16: Int16 = 0
    @objc dynamic var attrInteger32: Int32 = 0
    @objc dynamic var attrInteger64: Int64 = 0

}
