/* DO NOT EDIT | Generated by dbgenerator */

import RealmSwift

final class Shop: Object {

    enum Attributes: String {
        case AttrDate = "attrDate"
        case AttrDateCustom = "attrDateCustom"
        case AttrDecimal = "attrDecimal"
        case AttrDouble = "attrDouble"
        case AttrFloat = "attrFloat"
        case AttrInteger16 = "attrInteger16"
        case AttrInteger32 = "attrInteger32"
        case AttrInteger64 = "attrInteger64"
    }

    dynamic var attrDate: NSDate? = nil
    dynamic var attrDateCustom: NSDate? = nil
    dynamic var attrDecimal: Double = 0.0
    dynamic var attrDouble: Double = 0.0
    dynamic var attrFloat: Float = 0.0
    dynamic var attrInteger16: Int16 = 0
    dynamic var attrInteger32: Int32 = 0
    dynamic var attrInteger64: Int64 = 0

}
