/* DO NOT EDIT | Generated by gyro */

import RealmSwift
import Foundation

final class Shop: Object {

    enum Attributes: String {
        case AttrDate = "attrDate"
        case AttrDateCustom = "attrDateCustom"
        case AttrDecimal = "attrDecimal"
        case AttrDouble = "attrDouble"
        case AttrFloat = "attrFloat"
        case AttrInteger16 = "attrInteger16"
        case AttrInteger32 = "attrInteger32"
        case AttrInteger64 = "attrInteger64"
    }

    @objc dynamic var attrDate: NSDate? = nil
    @objc dynamic var attrDateCustom: NSDate? = nil
    @objc dynamic var attrDecimal: Double = 0.0
    @objc dynamic var attrDouble: Double = 0.0
    @objc dynamic var attrFloat: Float = 0.0
    @objc dynamic var attrInteger16: Int16 = 0
    @objc dynamic var attrInteger32: Int32 = 0
    @objc dynamic var attrInteger64: Int64 = 0

}
