// DO NOT EDIT | Generated by gyro

////////////////////////////////////////////////////////////////////////////////

#pragma mark - Imports

#import <Realm/Realm.h>

#pragma mark - Types

@class RLMUser;

#pragma mark - Defines & Constants

extern const struct RLMFidelityCardAttributes {
    __unsafe_unretained NSString *identifier;
    __unsafe_unretained NSString *points;
} RLMFidelityCardAttributes;

extern const struct RLMFidelityCardRelationships {
    __unsafe_unretained NSString *user;
} RLMFidelityCardRelationships;

////////////////////////////////////////////////////////////////////////////////

#pragma mark - Interface

@interface RLMFidelityCard : RLMObject

#pragma mark - Properties

@property int identifier;
@property long points;
@property RLMUser *user;

@end
