// DO NOT EDIT | Generated by gyro

////////////////////////////////////////////////////////////////////////////////

#pragma mark - Imports

#import <Realm/Realm.h>
#import "RLMTypes.h"
#import "RLMProtocols.h"

#pragma mark - Types

@class RLMProduct;

#pragma mark - Defines & Constants

extern const struct RLMShopAttributes {
    __unsafe_unretained NSString *name;
    __unsafe_unretained NSString *type;
} RLMShopAttributes;

extern const struct RLMShopRelationships {
    __unsafe_unretained NSString *products;
} RLMShopRelationships;

////////////////////////////////////////////////////////////////////////////////

#pragma mark - Interface

@interface RLMShop : RLMObject

#pragma mark - Properties

@property NSString *name;
@property RLMTypeA type;
@property RLMArray<RLMProduct> *products;

@end
