// DO NOT EDIT | Generated by gyro

////////////////////////////////////////////////////////////////////////////////

#pragma mark - Types

typedef NS_ENUM(int, RLMTypeA) {
    RLMTypeAOne = 0,
    RLMTypeATwo,
    RLMTypeAThree
};

typedef NS_ENUM(int, RLMTypeB) {
    RLMTypeBOne = 0,
    RLMTypeBTwo,
    RLMTypeBThree
};
