// DO NOT EDIT | Generated by gyro

////////////////////////////////////////////////////////////////////////////////

#pragma mark - Imports

#import <Realm/Realm.h>
#import "RLMTypes.h"

#pragma mark - Types

@class RLMFidelityCard;

#pragma mark - Defines & Constants

extern const struct RLMUserAttributes {
    __unsafe_unretained NSString *birthday;
    __unsafe_unretained NSString *name;
    __unsafe_unretained NSString *type;
} RLMUserAttributes;

extern const struct RLMUserRelationships {
    __unsafe_unretained NSString *fidelityCard;
} RLMUserRelationships;

////////////////////////////////////////////////////////////////////////////////

#pragma mark - Interface

@interface RLMUser : RLMObject

#pragma mark - Properties

@property NSDate *birthday;
@property NSString *name;
@property RLMTypeB type;
@property RLMFidelityCard *fidelityCard;

@end
