// DO NOT EDIT | Generated by dbgenerator

////////////////////////////////////////////////////////////////////////////////

#pragma mark - Imports

#import <Realm/Realm.h>

#pragma mark - Types

@class RLMShop;

#pragma mark - Defines & Constants

extern const struct RLMOwnerAttributes {
    __unsafe_unretained NSString *name;
} RLMOwnerAttributes;

extern const struct RLMOwnerRelationships {
    __unsafe_unretained NSString *shop;
} RLMOwnerRelationships;

////////////////////////////////////////////////////////////////////////////////

#pragma mark - Interface

@interface RLMOwner : RLMObject

#pragma mark - Properties

@property NSString *name;
@property RLMShop *shop;

@end
