// DO NOT EDIT | Generated by gyro

////////////////////////////////////////////////////////////////////////////////

#pragma mark - Imports

#import "RLMShop.h"

#pragma mark - Defines & Constants

const struct RLMShopAttributes RLMShopAttributes = {
    .ignored = @"ignored",
    .name = @"name",
    .readOnly = @"readOnly"
};

const struct RLMShopRelationships RLMShopRelationships = {
    .owner = @"owner",
    .products = @"products"
};

////////////////////////////////////////////////////////////////////////////////

#pragma mark - Implementation

@implementation RLMShop

#pragma mark - Superclass Overrides

// Specify required properties
+ (NSArray *)requiredProperties
{
    return @[@"ignored", @"name", @"readOnly"];
}

// Specify default values for required properties
+ (NSDictionary *)defaultPropertyValues
{
    return @{@"ignored" : @"", @"name" : @"", @"readOnly" : @""};
}

// Specify properties to ignore (Realm won't persist these)
+ (NSArray *)ignoredProperties
{
    return @[@"ignored"];
}

- (NSString *)readOnly
{
    return self.name;
}

@end
