// DO NOT EDIT | Generated by gyro

////////////////////////////////////////////////////////////////////////////////

#pragma mark - Imports

#import <Realm/Realm.h>
#import "RLMProtocols.h"

#pragma mark - Types

@class RLMOwner;
@class RLMProduct;

#pragma mark - Defines & Constants

extern const struct RLMShopAttributes {
    __unsafe_unretained NSString *ignored;
    __unsafe_unretained NSString *name;
    __unsafe_unretained NSString *readOnly;
} RLMShopAttributes;

extern const struct RLMShopRelationships {
    __unsafe_unretained NSString *owner;
    __unsafe_unretained NSString *products;
} RLMShopRelationships;

////////////////////////////////////////////////////////////////////////////////

#pragma mark - Interface

@interface RLMShop : RLMObject

#pragma mark - Properties

@property NSString *ignored;
@property NSString *name;
@property (readonly) NSString *readOnly;
@property RLMOwner *owner;
@property RLMArray<RLMProduct> *products;

@end
