package com.gyro.tests;

import io.realm.RealmObject;

/* DO NOT EDIT | Generated by gyro */

public class FidelityCard extends RealmObject {

    public interface Attributes {
        String IDENTIFIER = "identifier";
        String POINTS = "points";
    }

    public interface Relationships {
        String USER = "user";
    }

    private short identifier;
    @android.support.annotation.IntRange(from=0,to=255)
    private int points;
    private User user;

    public short getIdentifier() {
        return identifier;
    }

    public void setIdentifier(final short identifier) {
        this.identifier = identifier;
    }

    @android.support.annotation.IntRange(from=0,to=255)
    public int getPoints() {
        return points;
    }

    public void setPoints(@android.support.annotation.IntRange(from=0,to=255) final int points) {
        this.points = points;
    }

    @android.support.annotation.Nullable
    public User getUser() {
        return user;
    }

    public void setUser(@android.support.annotation.Nullable final User user) {
        this.user = user;
    }
}
