// DO NOT EDIT | Generated by dbgenerator

////////////////////////////////////////////////////////////////////////////////

#pragma mark - Imports

#import "RLMUser.h"

#pragma mark - Defines & Constants

const struct RLMUserAttributes RLMUserAttributes = {
    .birthday = @"birthday",
    .name = @"name"
};

const struct RLMUserRelationships RLMUserRelationships = {
    .fidelityCard = @"fidelityCard"
};

////////////////////////////////////////////////////////////////////////////////

#pragma mark - Implementation

@implementation RLMUser

#pragma mark - Superclass Overrides

// Specify required properties
+ (NSArray *)requiredProperties
{
    return @[@"birthday", @"name"];
}

// Specify default values for required properties
+ (NSDictionary *)defaultPropertyValues
{
    return @{@"birthday" : [NSDate date], @"name" : @""};
}

@end
