/* DO NOT EDIT | Generated by gyro */

import RealmSwift
import Foundation

final class Dog: Object {

  enum Attributes: String {
    static let age = "age"
    static let name = "name"
  }

  @objc dynamic var age: Int16 = 0
  @objc dynamic var name: String = ""
	
  let owners = LinkingObjects(fromType: Person.self, property: "dogs")
  var owner: Person? { return owners.first }

}
