/* DO NOT EDIT | Generated by dbgenerator */

import RealmSwift

class Dog : Object {

    enum Attributes : String {
        case Age = "age"
        case Name = "name"
    }

    dynamic var age = 0
    dynamic var name = ""

    var owner :Person {
        return linkingObjects(Person.self, forProperty: "dogs").first!
    }

}
