// DO NOT EDIT | Generated by dbgenerator

////////////////////////////////////////////////////////////////////////////////

#pragma mark - Types

typedef NS_ENUM(int, RLMType) {
    RLMTypeOne = 0,
    RLMTypeTwo,
    RLMTypeThree
};

typedef NS_ENUM(int, RLMType2) {
    RLMType2None = 0,
    RLMType2One,
    RLMType2Two,
    RLMType2Three
};
