// DO NOT EDIT | Generated by dbgenerator

////////////////////////////////////////////////////////////////////////////////

#pragma mark - Imports

#import "RLMProduct.h"

#pragma mark - Defines & Constants

const struct RLMProductAttributes RLMProductAttributes = {
    .brand = @"brand",
    .name = @"name",
    .price = @"price"
};

////////////////////////////////////////////////////////////////////////////////

#pragma mark - Implementation

@implementation RLMProduct

#pragma mark - Superclass Overrides

+ (NSString *)primaryKey
{
    return @"name";
}

// Specify required properties
+ (NSArray *)requiredProperties
{
    return @[@"brand", @"price"];
}

// Specify default values for required properties
+ (NSDictionary *)defaultPropertyValues
{
    return @{@"brand" : @"", @"price" : @(0)};
}

@end
