// DO NOT EDIT | Generated by dbgenerator

////////////////////////////////////////////////////////////////////////////////

#pragma mark - Imports

#import "RLMShop.h"

#pragma mark - Defines & Constants

const struct RLMShopAttributes RLMShopAttributes = {
    .name = @"name"
};

const struct RLMShopRelationships RLMShopRelationships = {
    .products = @"products"
};

////////////////////////////////////////////////////////////////////////////////

#pragma mark - Implementation

@implementation RLMShop

#pragma mark - Superclass Overrides

+ (NSString *)primaryKey
{
    return @"name";
}

@end
