// DO NOT EDIT | Generated by dbgenerator

////////////////////////////////////////////////////////////////////////////////

#pragma mark - Imports

#import "RLMProduct+JSON.h"

////////////////////////////////////////////////////////////////////////////////

#pragma mark - Implementation

@implementation RLMProduct (JSON)

+ (NSDictionary *)JSONInboundMappingDictionary
{
    return @{
        @"shop" : @"shop"
    };
}

+ (NSDictionary *)JSONOutboundMappingDictionary
{
    return @{
        @"shop" : @"shop"
    };
}

@end
