package com.gyro.tests;

import io.realm.RealmObject;

/* DO NOT EDIT | Generated by gyro */

public class Product extends RealmObject {

    public interface Relationships {
        String SHOP = "shop";
    }

    private Shop shop;

    public Shop getShop() {
        return shop;
    }

    public void setShop(final Shop shop) {
        this.shop = shop;
    }
}
