package com.gyro.tests

/* DO NOT EDIT | Generated by gyro */

import io.realm.RealmList
import io.realm.RealmObject
import io.realm.annotations.Required

class Shop : RealmObject() {

    object Attributes {
        const val NAME: String = "name"
        const val TYPE: String = "type"
    }

    object Relationships {
        const val PRODUCTS: String = "products"
    }

    @Required
    var name: String = ""
    @Required
    var type: String = "TypeAOne"
    var products: RealmList<Product>? = null

    fun  getTypeEnum(): TypeA? {
        return TypeA.get(type)
    }

    fun setTypeEnum(type: TypeA) {
        this.type = type.jsonValue
    }
}
