package com.gyro.tests

/* DO NOT EDIT | Generated by gyro */


enum class TypeA(val jsonValue: String) {

    TYPE_A_ONE("TypeAOne"),
    TYPE_A_TWO("TypeATwo"),
    TYPE_A_THREE("TypeAThree");

    companion object {
        @JvmStatic
        fun get(jsonValue: String): TypeA? {
            return TypeA.values().firstOrNull { it.jsonValue == jsonValue }
        }
    }
}
