package com.gyro.tests

/* DO NOT EDIT | Generated by gyro */


enum class TypeB(val jsonValue: String) {

    TYPE_B_ONE("TypeBOne"),
    TYPE_B_TWO("TypeBTwo"),
    TYPE_B_THREE("TypeBThree");

    companion object {
        @JvmStatic
        fun get(jsonValue: String): TypeB? {
            return TypeB.values().firstOrNull { it.jsonValue == jsonValue }
        }
    }
}
