/* DO NOT EDIT | Generated by gyro */

import RealmSwift
import Foundation

final class Product: Object {

  enum Attributes: String {
    case name = "name" /* Primary Key */
    case brand = "brand"
    case price = "price"
  }

  @objc dynamic var name: String = "" /* Primary Key */
  @objc dynamic var brand: String = ""
  @objc dynamic var price: Int32 = 0

  override static func primaryKey() -> String? {
    return "name"
  }

}
