/* DO NOT EDIT | Generated by gyro */

import RealmSwift
import Foundation

final class Shop: Object {

  enum Attributes: String {
    static let name = "name" /* Primary Key */
  }

  enum Relationships: String {
    static let products = "products"
  }

  @objc dynamic var name: String = "" /* Primary Key */
  let products = List<Product>()

  override static func primaryKey() -> String? {
    return "name"
  }

}
