/* DO NOT EDIT | Generated by gyro */

import RealmSwift

final class Shop: Object {

  enum Attributes: String {
    case name = "name"
  }

  enum Relationships: String {
    case products = "products"
  }

  dynamic var name: String = ""
  let products = List<Product>()

  override static func primaryKey() -> String? {
    return "name"
  }

}
