/* DO NOT EDIT | Generated by dbgenerator */

import RealmSwift

class User : Object {

    enum Attributes : String {
        case Birthday = "birthday"
        case Name = "name"
    }

    enum Relationships : String {
        case FidelityCard = "fidelityCard"
    }

    dynamic var birthday = NSDate()
    dynamic var name = ""
    dynamic var fidelityCard :FidelityCard?

    override static func primaryKey() -> String? {
        return "name"
    }

}
