package com.gyro.tests

/* DO NOT EDIT | Generated by gyro */

import io.realm.RealmObject
import io.realm.annotations.Required

open class Dog : RealmObject() {

    object Attributes {
        const val AGE: String = "age"
        const val NAME: String = "name"
    }

    var age: Short = 0
    @Required
    var name: String = ""
}
