// DO NOT EDIT | Generated by dbgenerator

////////////////////////////////////////////////////////////////////////////////

#pragma mark - Imports

#import "RLMProduct.h"

#pragma mark - Defines & Constants

const struct RLMProductRelationships RLMProductRelationships = {
    .shop = @"shop"
};

////////////////////////////////////////////////////////////////////////////////

#pragma mark - Implementation

@implementation RLMProduct

@end
