/* DO NOT EDIT | Generated by gyro */

import RealmSwift
import Foundation

/// Object representation from web service.
final class Shop: Object {

  enum Attributes: String {
    static let active = "active"
    static let budget = "budget"
    /// Define if this shop is open. This variable is updated every hours.
    static let isOpen = "isOpen"
    static let name = "name"
    static let numberOfArrivals = "numberOfArrivals"
    static let numberOfProducts = "numberOfProducts"
    static let promo = "promo"
    /// The company slogan about this shop
    static let slogan = "slogan"
  }

  enum Relationships: String {
    /// List of wholesaler
    static let wholesalers = "wholesalers"
  }

  @objc dynamic var active: Bool = true
  @objc dynamic var budget: Double = 26000.35
  @objc dynamic var isOpen: Bool = false
  @objc dynamic var name: String = ""
  @objc dynamic var numberOfArrivals: Int32 = 0
  @objc dynamic var numberOfProducts: Int32 = 155
  @objc dynamic var promo: Double = 0.0
  @objc dynamic var slogan: String = "The best place to be"
  let wholesalers = List<Shop>()

}
