/* DO NOT EDIT | Generated by gyro */

import RealmSwift
import Foundation

final class Shop: Object {

  enum Attributes: String {
    case active = "active"
    case isOpened = "isOpened"
    case isValid = "isValid"
    case name = "name"
    case promo = "promo"
  }

  dynamic var active: Bool = true
  dynamic var isOpened: Bool = false
  dynamic var isValid: Bool = false
  dynamic var name: String = ""
  dynamic var promo: Int32 = -1

}
