package com.gyro.tests;

/* DO NOT EDIT | Generated by gyro */


import io.realm.RealmObject;
import io.realm.annotations.PrimaryKey;

public class FidelityCard extends RealmObject {

    public static final class Attributes {
        private Attributes() {
            // Hide constructor
        }

        public static final String IDENTIFIER = "identifier";
        public static final String POINTS = "points";
    }

    public static final class Relationships {
        private Relationships() {
            // Hide constructor
        }

        public static final String USER = "user";
    }

    @PrimaryKey
    private short identifier;
    private int points;
    private User user;

    public short getIdentifier() {
        return identifier;
    }

    public void setIdentifier(final short identifier) {
        this.identifier = identifier;
    }

    public int getPoints() {
        return points;
    }

    public void setPoints(final int points) {
        this.points = points;
    }

    public User getUser() {
        return user;
    }

    public void setUser(final User user) {
        this.user = user;
    }
}
