package com.gyro.tests;

/* DO NOT EDIT | Generated by gyro */

import java.util.Date;

import io.realm.RealmObject;
import io.realm.annotations.PrimaryKey;

public class User extends RealmObject {

    public static final class Attributes {
        private Attributes() {
            // Hide constructor
        }

        public static final String BIRTHDAY = "birthday";
        public static final String NAME = "name";
    }

    public static final class Relationships {
        private Relationships() {
            // Hide constructor
        }

        public static final String FIDELITY_CARD = "fidelityCard";
    }

    private Date birthday;
    @PrimaryKey
    private String name;
    private FidelityCard fidelityCard;

    public Date getBirthday() {
        return birthday;
    }

    public void setBirthday(final Date birthday) {
        this.birthday = birthday;
    }

    public String getName() {
        return name;
    }

    public void setName(final String name) {
        this.name = name;
    }

    public FidelityCard getFidelityCard() {
        return fidelityCard;
    }

    public void setFidelityCard(final FidelityCard fidelityCard) {
        this.fidelityCard = fidelityCard;
    }
}
