/* DO NOT EDIT | Generated by dbgenerator */

import RealmSwift

class FidelityCard : Object {

    enum Attributes : String {
        case Identifier = "identifier"
        case Points = "points"
    }

    enum Relationships : String {
        case User = "user"
    }

    dynamic var identifier = 0
    dynamic var points = 0
    dynamic var user :User?

}
