/* DO NOT EDIT | Generated by gyro */

import RealmSwift

final class FidelityCard: Object {

    enum Attributes: String {
        case Identifier = "identifier"
        case Points = "points"
    }

    enum Relationships: String {
        case User = "user"
    }

    dynamic var identifier: Int16 = 0
    dynamic var points: Int32 = 0
    dynamic var user: User?

}
