/* DO NOT EDIT | Generated by gyro */

import RealmSwift
import Foundation

final class Product: Object {

  enum Attributes: String {
    static let brand = "brand"
    static let name = "name"
    static let price = "price"
  }

  @objc dynamic var brand: String = ""
  @objc dynamic var name: String = ""
  @objc dynamic var price: Int32 = 0

}
