// DO NOT EDIT | Generated by gyro

////////////////////////////////////////////////////////////////////////////////

#pragma mark - Protocols

// This protocol enables typed collections. i.e.: RLMArray<RLMProduct>
RLM_ARRAY_TYPE(RLMProduct)
