// DO NOT EDIT | Generated by gyro

////////////////////////////////////////////////////////////////////////////////

#pragma mark - Imports

#import "RLMAnimal+JSON.h"

////////////////////////////////////////////////////////////////////////////////

#pragma mark - Implementation

@implementation RLMAnimal (JSON)

+ (NSDictionary *)JSONInboundMappingDictionary
{
    return @{
        @"attribute" : @"attribute",
        @"relationshipNoValue" : @"relationshipNoValue"
    };
}

+ (NSDictionary *)JSONOutboundMappingDictionary
{
    return @{
        @"attribute" : @"attribute",
        @"relationshipNoValue" : @"relationshipNoValue"
    };
}

@end
