// DO NOT EDIT | Generated by dbgenerator

////////////////////////////////////////////////////////////////////////////////

#pragma mark - Imports

#import "RLMAnimal.h"

#pragma mark - Defines & Constants

const struct RLMAnimalAttributes RLMAnimalAttributes = {
    .attribute = @"attribute"
};

const struct RLMAnimalRelationships RLMAnimalRelationships = {
    .relationshipNoValue = @"relationshipNoValue"
};

////////////////////////////////////////////////////////////////////////////////

#pragma mark - Implementation

@implementation RLMAnimal

#pragma mark - Superclass Overrides

@end
