// DO NOT EDIT | Generated by dbgenerator

////////////////////////////////////////////////////////////////////////////////

#pragma mark - Imports

#import <Realm/Realm.h>
#import "RLMProtocols.h"

#pragma mark - Defines & Constants

extern const struct RLMAnimalAttributes {
    __unsafe_unretained NSString *attribute;
} RLMAnimalAttributes;

extern const struct RLMAnimalRelationships {
    __unsafe_unretained NSString *relationshipNoValue;
} RLMAnimalRelationships;

////////////////////////////////////////////////////////////////////////////////

#pragma mark - Interface

@interface RLMAnimal : RLMObject

#pragma mark - Properties

@property NSString *attribute;
@property NSArray<NSString *> *relationshipNoValue;

@end
