=begin
Copyright 2016 - Niji

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
=end

module DBGenerator
  module Realm
    module Java
      module Templates

        # ANNOTATIONS
        PRIMARY_KEY_ANNOTATION = '@PrimaryKey'
        INDEXED_ANNOTATION = '@Index'
        IGNORED_ANNOTATION = '@Ignore'
        GSON_ANNOTATION = "@SerializedName(\"%s\")"
        SUPPORT_ANNOTATION = "@android.support.annotation.%s"

        # COMMONS
        PACKAGE_TEMPLATE = 'package %s;'
        JAVA_FILE_TEMPLATE = '%s.java'
        GENERATED_MESSAGE = '/* DO NOT EDIT | Generated by dbgenerator */'

        # IMPORTS
        IMPORT_DATE = 'import java.util.Date;'
        IMPORT_LIST = 'import java.util.List;'
        IMPORT_GSON = 'import com.google.gson.annotations.SerializedName;'
        IMPORT_REALM_LIST = 'import io.realm.RealmList;'
        IMPORT_REALM_OBJECT = 'import io.realm.RealmObject;'
        IMPORT_REALM_IGNORE = 'import io.realm.annotations.Ignore;'
        IMPORT_REALM_INDEX = 'import io.realm.annotations.Index;'
        IMPORT_REALM_PRIMARY_KEY = 'import io.realm.annotations.PrimaryKey;'

        # ENUM
        ENUM_TEMPLATE = 'public enum %s {'
        ENUM_JSON_VALUE = "(\"%s\")"

        # CLASS
        CLASS_TEMPLATE = 'public class %s extends RealmObject {'
        ATTRIBUTE_TEMPLATE = 'private %s %s;'
        FINAL_ATTRIBUTE_TEMPLATE = 'private final %s %s;'
        REALM_LIST_TEMPLATE = 'RealmList<%s>'
        LIST_TEMPLATE = 'List<%s>'

        # CONSTANTS
        ATTRIBUTE_CONSTANTS = 'public interface Attributes {'
        RELATIONSHIP_CONSTANTS = 'public interface Relationships {'
        CONSTANT_TEMPLATE = 'String %s = "%s";'

        # COMMENTS
        CLASS_COMMENT_TEMPLATE = "/**\n * %s\n */"
        ATTRIBUTE_COMMENT_TEMPLATE = '/** %s */'

      end
    end
  end
end
