module DBGenerator
  module Realm
    module Java
      module Templates

        # ANNOTATIONS
        PRIMARY_KEY_ANNOTATION = '@PrimaryKey'
        INDEXED_ANNOTATION = '@Index'
        IGNORED_ANNOTATION = '@Ignore'
        GSON_ANNOTATION = "@SerializedName(\"%s\")"

        # COMMONS
        PACKAGE_TEMPLATE = 'package %s;'
        JAVA_FILE_TEMPLATE = '%s.java'
        GENERATED_MESSAGE = '/* DO NOT EDIT | Generated by dbgenerator */'

        # IMPORTS
        IMPORT_DATE = 'import java.util.Date;'
        IMPORT_LIST = 'import java.util.List;'
        IMPORT_GSON = 'import com.google.gson.annotations.SerializedName;'
        IMPORT_REALM_LIST = 'import io.realm.RealmList;'
        IMPORT_REALM_OBJECT = 'import io.realm.RealmObject;'
        IMPORT_REALM_IGNORE = 'import io.realm.annotations.Ignore;'
        IMPORT_REALM_INDEX = 'import io.realm.annotations.Index;'
        IMPORT_REALM_PRIMARY_KEY = 'import io.realm.annotations.PrimaryKey;'

        # ENUM
        ENUM_TEMPLATE = 'public enum %s {'
        ENUM_JSON_VALUE = "(\"%s\")"

        # CLASS
        CLASS_TEMPLATE = 'public class %s extends RealmObject {'
        ATTRIBUTE_TEMPLATE = 'private %s %s;'
        REALM_LIST_TEMPLATE = 'RealmList<%s>'
        LIST_TEMPLATE = 'List<%s>'

        # CONSTANTS
        ATTRIBUTE_CONSTANTS = 'public interface Attributes {'
        RELATIONSHIP_CONSTANTS = 'public interface Relationships {'
        CONSTANT_TEMPLATE = 'String %s = "%s";'

        # COMMENTS
        CLASS_COMMENT_TEMPLATE = "/**\n * %s\n */"
        ATTRIBUTE_COMMENT_TEMPLATE = '/** %s */'

      end
    end
  end
end
