package com.gyro.tests;

/* DO NOT EDIT | Generated by gyro */

import io.realm.RealmObject;

public class Shop extends RealmObject {

    public static final class Attributes {
        public static final String ACTIVE = "active";
        public static final String IS_OPENED = "isOpened";
        public static final String IS_VALID = "isValid";
        public static final String NAME = "name";
        public static final String PROMO = "promo";

        private Attributes() {
            // Hide constructor
        }
    }

    private boolean active;
    private boolean isOpened;
    private boolean isValid;
    private String name;
    private int promo;

    public boolean getActive() {
        return active;
    }

    public void setActive(final boolean active) {
        this.active = active;
    }

    public boolean getIsOpened() {
        return isOpened;
    }

    public void setIsOpened(final boolean isOpened) {
        this.isOpened = isOpened;
    }

    public boolean getIsValid() {
        return isValid;
    }

    public void setIsValid(final boolean isValid) {
        this.isValid = isValid;
    }

    public String getName() {
        return name;
    }

    public void setName(final String name) {
        this.name = name;
    }

    public int getPromo() {
        return promo;
    }

    public void setPromo(final int promo) {
        this.promo = promo;
    }
}
