package com.gyro.tests;

/* DO NOT EDIT | Generated by gyro */

import io.realm.RealmObject;
import io.realm.annotations.Required;

public class Shop extends RealmObject {

    public static final class Attributes {
        public static final String ACTIVE = "active";
        public static final String BUDGET = "budget";
        public static final String IS_OPEN = "isOpen";
        public static final String NAME = "name";
        public static final String NUMBER_OF_ARRIVALS = "numberOfArrivals";
        public static final String NUMBER_OF_PRODUCTS = "numberOfProducts";
        public static final String PROMO = "promo";
        public static final String SLOGAN = "slogan";

        private Attributes() {
            // Hide constructor
        }
    }

    private boolean active = true;
    private double budget = 26000.35;
    private boolean isOpen;
    @Required
    private String name;
    private int numberOfArrivals;
    private int numberOfProducts = 155;
    private double promo;
    @Required
    private String slogan = "The best place to be";

    public boolean getActive() {
        return active;
    }

    public void setActive(final boolean active) {
        this.active = active;
    }

    public double getBudget() {
        return budget;
    }

    public void setBudget(final double budget) {
        this.budget = budget;
    }

    public boolean getIsOpen() {
        return isOpen;
    }

    public void setIsOpen(final boolean isOpen) {
        this.isOpen = isOpen;
    }

    public String getName() {
        return name;
    }

    public void setName(final String name) {
        this.name = name;
    }

    public int getNumberOfArrivals() {
        return numberOfArrivals;
    }

    public void setNumberOfArrivals(final int numberOfArrivals) {
        this.numberOfArrivals = numberOfArrivals;
    }

    public int getNumberOfProducts() {
        return numberOfProducts;
    }

    public void setNumberOfProducts(final int numberOfProducts) {
        this.numberOfProducts = numberOfProducts;
    }

    public double getPromo() {
        return promo;
    }

    public void setPromo(final double promo) {
        this.promo = promo;
    }

    public String getSlogan() {
        return slogan;
    }

    public void setSlogan(final String slogan) {
        this.slogan = slogan;
    }
}
