package com.gyro.tests

/* DO NOT EDIT | Generated by gyro */

import io.realm.RealmObject
import io.realm.annotations.Ignore
import io.realm.annotations.Required

class Owner : RealmObject() {

    object Attributes {
        const val NAME: String = "name"
    }

    object Relationships {
        const val SHOP: String = "shop"
    }

    var name: String? = null
    @Ignore
    var shop: Shop? = null
}
