package com.gyro.tests

/* DO NOT EDIT | Generated by gyro */

import io.realm.RealmList
import io.realm.RealmObject
import io.realm.annotations.Ignore
import io.realm.annotations.Required

class Shop : RealmObject() {

    object Attributes {
        const val NAME: String = "name"
        const val READ_ONLY: String = "readOnly"
    }

    object Relationships {
        const val OWNER: String = "owner"
        const val PRODUCTS: String = "products"
    }

    @Ignore
    var ignored: String = ""
    @Ignore
    var ignored2: String = ""
    @Required
    var name: String = ""
    var owner: Owner? = null
    var products: RealmList<Product>? = null
}
