package com.gyro.tests;

import io.realm.RealmObject;

/* DO NOT EDIT | Generated by gyro */

public class FidelityCard extends RealmObject {

    public static class Attributes {
        private Attributes() {
            // Hide constructor
        }
        
        public static final String IDENTIFIER = "identifier";
        public static final String POINTS = "points";
    }

    public static class Relationships {
        private Relationships() {
            // Hide constructor
        }
        
        public static final String USER = "user";
    }

    private Short identifier;
    @android.support.annotation.IntRange(from=0,to=255)
    private Integer points;
    private User user;

    public Short getIdentifier() {
        return identifier;
    }

    public void setIdentifier(final Short identifier) {
        this.identifier = identifier;
    }

    @android.support.annotation.IntRange(from=0,to=255)
    public Integer getPoints() {
        return points;
    }

    public void setPoints(@android.support.annotation.IntRange(from=0,to=255) final Integer points) {
        this.points = points;
    }

    public User getUser() {
        return user;
    }

    public void setUser(final User user) {
        this.user = user;
    }
}
