package com.gyro.tests;

import io.realm.RealmList;
import io.realm.RealmObject;

/* DO NOT EDIT | Generated by gyro */

public class Shop extends RealmObject {

    public static class Attributes {
        private Attributes() {
            // Hide constructor
        }
        
        public static final String NAME = "name";
    }
    
    public static class Relationships {
        private Relationships() {
            // Hide constructor
        }
        
        public static final String PRODUCTS = "products";
    }

    private String name;
    private RealmList<Product> products;

    public String getName() {
        return name;
    }

    public void setName(final String name) {
        this.name = name;
    }

    public RealmList<Product> getProducts() {
        return products;
    }

    public void setProducts(final RealmList<Product> products) {
        this.products = products;
    }
}
