package fr.ganfra.realm;

import io.realm.RealmList;
import io.realm.RealmObject;
import io.realm.annotations.Ignore;

/* DO NOT EDIT | Generated by dbgenerator */

public class Shop extends RealmObject {

    public interface Attributes {
        String NAME = "name";
        String TYPE = "type";
    }

    public interface Relationships {
        String PRODUCTS = "products";
    }

    private String name;
    @Ignore
    private TypeA typeEnum;
    private String type;
    private RealmList<Product> products;

    public String getName() {
        return name;
    }

    public void setName(final String name) {
        this.name = name;
    }

    public String getType() {
        return type;
    }

    public void setType(final String type) {
        this.type = type;
    }

    public TypeA getTypeEnum() {
        return TypeA.get(getType());
    }

    public void setTypeEnum(final TypeA type) {
        this.type = type.getJsonValue();
    }

    public RealmList<Product> getProducts() {
        return products;
    }

    public void setProducts(final RealmList<Product> products) {
        this.products = products;
    }
}
