package fr.ganfra.realm;

/* DO NOT EDIT | Generated by dbgenerator */

public enum TypeB {

    TYPE_ONE("type_b_one"),
    TYPE_TWO("type_b_two"),
    TYPE_THREE("type_b_three");

    private String jsonValue;

    TypeB(String jsonValue) {
        this.jsonValue = jsonValue;
    }

    public static TypeB get(String jsonValue) {
        for (TypeB type : TypeB.values()) {
            if (type.getJsonValue().equals(jsonValue)) {
                return type;
            }
        }
        return null;
    }

    public String getJsonValue() {
        return jsonValue;
    }
}
