package com.gyro.tests;
/* DO NOT EDIT | Generated by gyro */

public enum TypeB {

    TYPE_B_ONE("TypeBOne"),
    TYPE_B_TWO("TypeBTwo"),
    TYPE_B_THREE("TypeBThree");

    private final String jsonValue;

    TypeB(final String jsonValue) {
        this.jsonValue = jsonValue;
    }

    public static TypeB get(final String jsonValue) {
        for (final TypeB type : TypeB.values()) {
            if (type.getJsonValue().equals(jsonValue)) {
                return type;
            }
        }
        return null;
    }

    public String getJsonValue() {
        return jsonValue;
    }

}
