package com.gyro.tests;
/* DO NOT EDIT | Generated by gyro */

public enum TypeA {

    TYPE_A_ONE("TypeAOne"),
    TYPE_A_TWO("TypeATwo"),
    TYPE_A_THREE("TypeAThree");

    private final String jsonValue;

    TypeA(final String jsonValue) {
        this.jsonValue = jsonValue;
    }

    public static TypeA get(final String jsonValue) {
        for (final TypeA type : TypeA.values()) {
            if (type.getJsonValue().equals(jsonValue)) {
                return type;
            }
        }
        return null;
    }

    public String getJsonValue() {
        return jsonValue;
    }

}
