package fr.ganfra.realm;

/* DO NOT EDIT | Generated by dbgenerator */

public enum TypeA {

    TYPE_ONE("type_a_one"),
    TYPE_TWO("type_a_two"),
    TYPE_THREE("type_a_three");

    private String jsonValue;

    TypeA(String jsonValue) {
        this.jsonValue = jsonValue;
    }

    public static TypeA get(String jsonValue) {
        for (TypeA type : TypeA.values()) {
            if (type.getJsonValue().equals(jsonValue)) {
                return type;
            }
        }
        return null;
    }

    public String getJsonValue() {
        return jsonValue;
    }
}
