package com.gyro.tests;

import java.util.Date;

import io.realm.RealmObject;
import io.realm.annotations.Ignore;

/* DO NOT EDIT | Generated by gyro */

public class User extends RealmObject {

    public interface Attributes {
        String BIRTHDAY = "birthday";
        String NAME = "name";
        String TYPE = "type";
    }

    public interface Relationships {
        String FIDELITY_CARD = "fidelityCard";
    }

    private Date birthday;
    private String name;
    @Ignore
    private TypeB typeEnum;
    private String type;
    private FidelityCard fidelityCard;

    public Date getBirthday() {
        return birthday;
    }

    public void setBirthday(final Date birthday) {
        this.birthday = birthday;
    }

    public String getName() {
        return name;
    }

    public void setName(final String name) {
        this.name = name;
    }

    public String getType() {
        return type;
    }

    public void setType(final String type) {
        this.type = type;
    }

    public TypeB getTypeEnum() {
        return TypeB.get(getType());
    }

    public void setTypeEnum(final TypeB type) {
        this.type = type.getJsonValue();
    }

    public FidelityCard getFidelityCard() {
        return fidelityCard;
    }

    public void setFidelityCard(final FidelityCard fidelityCard) {
        this.fidelityCard = fidelityCard;
    }
}
