// DO NOT EDIT | Generated by gyro

////////////////////////////////////////////////////////////////////////////////

#pragma mark - Imports

#import "RLMShop+JSON.h"
#import "RLMTypes.h"

////////////////////////////////////////////////////////////////////////////////

#pragma mark - Implementation

@implementation RLMShop (JSON)

+ (NSDictionary *)JSONInboundMappingDictionary
{
    return @{
        @"name" : @"name",
        @"type" : @"type",
        @"type" : @"typeOptional"
    };
}

+ (NSDictionary *)JSONOutboundMappingDictionary
{
    return @{
        @"name" : @"name",
        @"type" : @"type",
        @"typeOptional" : @"type"
    };
}

+ (NSValueTransformer *)typeJSONTransformer
{
    return [MCJSONValueTransformer valueTransformerWithMappingDictionary:@{
        @"null" : @(RLMTypeOne),
        [NSNull null] : @(RLMTypeOne),
        @"<null>" : @(RLMTypeOne),
        @"" : @(RLMTypeOne),
        @"json_type_one" : @(RLMTypeOne),
        @"json_type_two" : @(RLMTypeTwo),
        @"json_type_three" : @(RLMTypeThree)
    }];
}

+ (NSValueTransformer *)typeOptionalJSONTransformer
{
    return [MCJSONValueTransformer valueTransformerWithMappingDictionary:@{
        @"null" : @(RLMType2None),
        [NSNull null] : @(RLMType2None),
        @"<null>" : @(RLMType2None),
        @"" : @(RLMType2None),
        @"json_type_one" : @(RLMType2One),
        @"json_type_two" : @(RLMType2Two),
        @"json_type_three" : @(RLMType2Three)
    }];
}

@end
