package fr.ganfra.realm;

import java.util.Date;

import io.realm.RealmObject;

/* DO NOT EDIT | Generated by dbgenerator */

public class User extends RealmObject {

    public interface Attributes {
        String BIRTHDAY = "birthday";
        String NAME = "name";
    }

    public interface Relationships {
        String FIDELITY_CARD = "fidelityCard";
    }

    private Date birthday;
    private String name;
    private FidelityCard fidelityCard;

    @android.support.annotation.NonNull
    public Date getBirthday() {
        return birthday;
    }

    public void setBirthday(@android.support.annotation.NonNull final Date birthday) {
        this.birthday = birthday;
    }

    @android.support.annotation.NonNull
    public String getName() {
        return name;
    }

    public void setName(@android.support.annotation.NonNull final String name) {
        this.name = name;
    }

    @android.support.annotation.Nullable
    public FidelityCard getFidelityCard() {
        return fidelityCard;
    }

    public void setFidelityCard(@android.support.annotation.Nullable final FidelityCard fidelityCard) {
        this.fidelityCard = fidelityCard;
    }
}
