package com.gyro.tests

/* DO NOT EDIT | Generated by gyro */

import java.util.List

import io.realm.RealmList
import io.realm.RealmObject
import io.realm.annotations.Required

class Animal : RealmObject() {

    object Attributes {
        const val ATTRIBUTE: String = "attribute"
    }

    object Relationships {
        const val RELATIONSHIP_NO_VALUE: String = "relationshipNoValue"
    }

    var attribute: String? = null
    var relationshipNoValue: List<String>? = null
}
