package fr.ganfra.realm;

import io.realm.RealmObject;
import io.realm.annotations.Ignore;

/* DO NOT EDIT | Generated by dbgenerator */

public class Shop extends RealmObject {

    public interface Attributes {
        String NAME = "name";
        String TYPE = "type";
    }

    private String name;
    @Ignore
    private Type typeEnum;
    private String type;

    public String getName() {
        return name;
    }

    public void setName(final String name) {
        this.name = name;
    }

    public String getType() {
        return type;
    }

    public void setType(final String type) {
        this.type = type;
    }

    public Type getTypeEnum() {
        return Type.get(getType());
    }

    public void setTypeEnum(Type type) {
        this.type = type.getJsonValue();
    }
}
