package fr.ganfra.realm;

/* DO NOT EDIT | Generated by dbgenerator */

public enum Type {

    TYPE_ONE("type_one"),
    TYPE_TWO("type_two"),
    TYPE_THREE("type_three");

    private String jsonValue;

    Type(String jsonValue) {
        this.jsonValue = jsonValue;
    }

    public static Type get(String jsonValue) {
        for (Type type : Type.values()) {
            if (type.getJsonValue().equals(jsonValue)) {
                return type;
            }
        }
        return null;
    }

    public String getJsonValue() {
        return jsonValue;
    }
}
