package com.gyro.tests;

/* DO NOT EDIT | Generated by gyro */

public enum Type {

    TYPE_ONE("TypeOne"),
    TYPE_TWO("TypeTwo"),
    TYPE_THREE("TypeThree");

    private final String jsonValue;

    Type(final String jsonValue) {
        this.jsonValue = jsonValue;
    }

    public static Type get(final String jsonValue) {
        for (final Type type : Type.values()) {
            if (type.getJsonValue().equals(jsonValue)) {
                return type;
            }
        }
        return null;
    }

    public String getJsonValue() {
        return jsonValue;
    }
}
