/* DO NOT EDIT | Generated by gyro */

import RealmSwift
import Foundation

final class FidelityCard: Object {

  enum Attributes: String {
    static let identifier = "identifier"
    static let points = "points"
  }

  enum Relationships: String {
    static let user = "user"
  }

  @objc dynamic var identifier: Int16 = 0
  let points = RealmOptional<Int32>()
  @objc dynamic var user: User?

}
