/* DO NOT EDIT | Generated by gyro */

import RealmSwift
import Foundation

final class Product: Object {

  enum Attributes: String {
    case brand = "brand"
    case name = "name"
    case price = "price"
  }

  @objc dynamic var brand: String?
  @objc dynamic var name: String = ""
  let price = RealmOptional<Int32>()

}
