/* DO NOT EDIT | Generated by dbgenerator */

import RealmSwift

final class User: Object {

    enum Attributes: String {
        case Birthday = "birthday"
        case Name = "name"
    }

    enum Relationships: String {
        case FidelityCard = "fidelityCard"
    }

    dynamic var birthday: NSDate = NSDate()
    dynamic var name: String = ""
    dynamic var fidelityCard: FidelityCard?

}
