/* DO NOT EDIT | Generated by gyro */

import RealmSwift
import Foundation

final class User: Object {

  enum Attributes: String {
    static let birthday = "birthday"
    static let name = "name"
  }

  enum Relationships: String {
    static let fidelityCard = "fidelityCard"
  }

  @objc dynamic var birthday: Date = Date()
  @objc dynamic var name: String = ""
  @objc dynamic var fidelityCard: FidelityCard?

}
