/* DO NOT EDIT | Generated by gyro */

import RealmSwift

final class User: Object {

  enum Attributes: String {
    case birthday = "birthday"
    case name = "name"
  }

  enum Relationships: String {
    case fidelityCard = "fidelityCard"
  }

  dynamic var birthday: NSDate = NSDate()
  dynamic var name: String = ""
  dynamic var fidelityCard: FidelityCard?

}
