package com.gyro.tests;

/* DO NOT EDIT | Generated by gyro */

import io.realm.RealmObject;

public class Product extends RealmObject {

    public static final class Relationships {
        public static final String SHOP = "shop";

        private Relationships() {
            // Hide constructor
        }
    }

    private Shop shop;

    public Shop getShop() {
        return shop;
    }

    public void setShop(final Shop shop) {
        this.shop = shop;
    }
}
