package com.gyro.tests;

import com.google.gson.annotations.SerializedName;

import io.realm.RealmObject;
import io.realm.annotations.Ignore;

/* DO NOT EDIT | Generated by gyro */

public class Shop extends RealmObject {

    public static class Attributes {
        private Attributes() {
            // Hide constructor
        }
        public static final String NAME = "name";
        public static final String TYPE = "type";
        public static final String TYPE_OPTIONAL = "typeOptional";
    }

    private String name;
    @Ignore
    private Type typeEnum;
    @SerializedName("type")
    private String type;
    @Ignore
    private Type2 typeOptionalEnum;
    @SerializedName("type")
    private String typeOptional;

    public String getName() {
        return name;
    }

    public void setName(final String name) {
        this.name = name;
    }

    public String getType() {
        return type;
    }

    public void setType(final String type) {
        this.type = type;
    }

    public String getTypeOptional() {
        return typeOptional;
    }

    public void setTypeOptional(final String typeOptional) {
        this.typeOptional = typeOptional;
    }

    public Type getTypeEnum() {
        return Type.get(getType());
    }

    public void setTypeEnum(final Type type) {
        this.type = type.getJsonValue();
    }

    public Type2 getTypeOptionalEnum() {
        return Type2.get(getTypeOptional());
    }

    public void setTypeOptionalEnum(final Type2 typeOptional) {
        this.typeOptional = typeOptional.getJsonValue();
    }
}
